// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl0-sz9xNN63xvmCmOYcEZhWRm-1KplZM',
    appId: '1:840590649290:web:93c3c900efc35e62d41133',
    messagingSenderId: '840590649290',
    projectId: 'zaapo-e368e',
    authDomain: 'zaapo-e368e.firebaseapp.com',
    storageBucket: 'zaapo-e368e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB56nSzvXaQBnDFA45TzbiD5n391hmp6uo',
    appId: '1:840590649290:android:33d63450c7043cf7d41133',
    messagingSenderId: '840590649290',
    projectId: 'zaapo-e368e',
    storageBucket: 'zaapo-e368e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYAdSQaG5pRTXo7rmZ5LTiBm7U6Tz_IQk',
    appId: '1:840590649290:ios:fb0512e27e9e5e03d41133',
    messagingSenderId: '840590649290',
    projectId: 'zaapo-e368e',
    storageBucket: 'zaapo-e368e.appspot.com',
    iosBundleId: 'com.example.loginForm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYAdSQaG5pRTXo7rmZ5LTiBm7U6Tz_IQk',
    appId: '1:840590649290:ios:546cf8fc28c44a89d41133',
    messagingSenderId: '840590649290',
    projectId: 'zaapo-e368e',
    storageBucket: 'zaapo-e368e.appspot.com',
    iosBundleId: 'com.example.loginForm.RunnerTests',
  );
}
